const languageCodeMap: { [key: string]: string } = {
    bengali: 'bn',
    bulgarian: 'bg',
    croatian: 'hr',
    czech: 'cs',
    danish: 'da',
    dutch: 'nl',
    english: 'en',
    estonian: 'et',
    french: 'fr',
    greek: 'el',
    gujarati: 'gu',
    hindi: 'hi',
    hungarian: 'hu',
    iranianPersian: 'fa',
    italian: 'it',
    japanese: 'ja',
    javanese: 'jv',
    kannada: 'kn',
    korean: 'ko',
    latvian: 'lv',
    lithuanian: 'lt',
    malayalam: 'ml',
    maltese: 'mt',
    mandarin: 'zh',
    manipuri: 'mni',
    odia: 'or',
    punjabi: 'pa',
    romanian: 'ro',
    russian: 'ru',
    santali: 'sat',
    slovenian: 'sl',
    spanish: 'es',
    swedish: 'sv',
    tamil: 'ta',
    telugu: 'te',
    thai: 'th',
    turkish: 'tr',
    urdu: 'ur',
    vietnamese: 'vi',
    welsh: 'cy'
};

export const getLanguageCode = (language: string): string => {
    return languageCodeMap[language] || language; // Fallback to the original name if not found
};